#!/usr/bin/env python

# Location of mapping generated for new release. Usually it's created by CLIVE from JSONSchema
# Used by schema_evolution.py
RELEASE_MAPPING = "release/model_b_collections.csv"

# The new mapping generated by schema_evolution.py when --init flag is on
# Incremental_transform.py uses this mapping when --init flag is on to initiate incremental load
BASE_MAPPING = "model_b_collections.csv"

# Schema_evolution.py outputs the new mapping by mering base and release mappings (--init is disabled)
# Incremental_transform.py uses it to generate sql transform scripts and update table partitions
DELTA_MAPPING = "model_b_collections-delta.csv"

# Incremental_transform.py generates sql transforms script and execute them
SQL_TRANFORM_SCRIPT  = "model_b_collections.sql"

# Location of managed hive databases
# Used by incremental_transform.py to copy transformed data to unmanaged partitions and to generate AVRO schema from files
HIVE_WAREHOUSE_DATA_LOCATION = "/apps/hive/warehouse"

# Incremental load is implemented using external tables. This parameter is the location for external tables
# Used only by incremental_transform.py
EXTERNAL_DATA_LOCATION = "/user/chrisrozacki/incremental"

# HDFS location of delta partition used by incremental_transform.py
SOURCE_DELTA_FOLDER_LOCATION = "/etl/uc/mongo_incremental/landing/delta/core/conract/${hiveconf:PARTITION}"

# Used during --init. HDFS location of delta partition used by incremental_transform.py
# mongo bulk is not partitioned hence ingest date used as parameter
SOURCE_BULK_FOLDER_LOCATION = "/etl/uc/mongo/${hiveconf:INGEST_DATE}"

# During --init, this BULK_TRANSFORMATION_PARAMETER_NAME is used, otherwise DELTA_TRANSFORMATION_PARAMETER_NAME
# This is parameter name passed to hive --hiveconf ...
DELTA_TRANSFORMATION_PARAMETER_NAME = "PARTITION"
BULK_TRANSFORMATION_PARAMETER_NAME = "INGEST_DATE"

# During --init BULK_INGEST_DAY is used to provide ingestion date, otherwise DELTA_PARTITION is used
# This parameter is used with conjunction with
DELTA_PARTITION = "2018-01-17"
BULK_INGEST_DAY = "2018-01-16"

# Working database name
DATABASE_NAME = "uc_dev_chris"

# Suffix used by schema_evolution.py to append to target table names. All delta target tables will have this suffix to
# distinguish from the incremental tables. Delta target tables are transient tables.
# BULK_TABLE_SUFFIX which is used during --init can stay empty as prior to --init there is no tables.
DELTA_TABLE_SUFFIX  =   "_delta"
BULK_TABLE_SUFFIX   =   ""

# Location of avros-tools used to extract avro schema from files
AVRO_TOOLS_LOCATION = "./avro-tools-1.8.1.jar"

# avro-tool requires a data file to be available in local file system to run getschema. This parameter is to provide the location
# where to copy the data file.
HDFS_AVROSCHEMAS_LOCATION = "/user/chrisrozacki/incremental/avroschema"
